# Generated by Django 3.2.25 on 2024-04-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_rename_advert_adoption_advert_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption',
            old_name='advert_id',
            new_name='advert',
        ),
    ]
